[project]
name = "bitmap-approach"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "loguru>=0.7.3",
    "matplotlib>=3.10.8",
    "orjson>=3.11.5",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
    "regex>=2025.11.3",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]
