[project]
name = "cs-jp-lp-benchmark"
version = "0.1.0"
description = "Benchmark CS-JP-LP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pulp>=2.7.0",
    "loguru>=0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
